### ISSUE TITLE
Can't flash on BHT-002-GCLW

### ISSUE THREAD

**Issue by JinKanzaki** [fashberg/WThermostatBeca#109]
So, I, for the life of me, can't get esptool to connect with the thermostat. I'm not great at soldering, so please excuse the mess but here are two pictures.
What  did I do wrong (aside from being too lazy to use the same colors for all VCC and GND connections, respectively)?
Does anyone know?

![IMG_20210228_171837](https://user-images.githubusercontent.com/40829950/109425872-c9ce9800-79ea-11eb-9dad-c361704dfdc4.jpg)
![IMG_20210228_171847](https://user-images.githubusercontent.com/40829950/109425910-eff43800-79ea-11eb-832c-2368f3474903.jpg)

**Comment by JinKanzaki** [comment]
I figured it out, I needed an external PSU since the FTDI adapter couldn't give me the necessary milliamps. Needs 60 mA.

**Comment by budisek** [comment]
Hi

may i know how did you connect TYWE3S with FTDI232? I have all wires soldered correctly. I am trying to connect it with Tasmotizer software but it can't recognize device at all.
