### ISSUE TITLE
Get Schedules

### ISSUE THREAD

**Issue by clemensloebig** [fashberg/WThermostatBeca#123]
Getting schedules isn't working with URL

`<device_ip>/stat/things/thermostat/schedules`

on BHT-002-GBLW

**Comment by beppexx80** [comment]
There is another way?

**Comment by paulius2k** [comment]
> There is another way?

MQTT: 
Request actual schedules via message with empty payload to <your_topic>/cmnd/things/thermostat/schedules, answers are reported to <your_topic>/stat/things/thermostat/schedules
https://github.com/fashberg/WThermostatBeca#2-schedules
