### ISSUE TITLE
BHT - 003 Beok or AVATTO

### ISSUE THREAD

**Issue by flayy73** [fashberg/WThermostatBeca#125]
Hi all, I would like to know if someonr tested this firmware on the BHT-003

![Immagine 2021-06-18 091529](https://user-images.githubusercontent.com/86019626/122522109-e16f7200-d015-11eb-9320-5a2bafc4ef46.jpg)

If yes, with Tuya convert or by soldering ?

**Comment by pfunkowski** [comment]
i have that thermostat, i dont try tuya convert - flash with soldering and work perfectly

**Comment by maxdd** [comment]
> i have that thermostat, i dont try tuya convert - flash with soldering and work perfectly

@pfunkowski
Is the chip a WBR3 or a BK7231?
