### ISSUE TITLE
Home Assistant graph

### ISSUE THREAD

**Issue by iMike78** [fashberg/WThermostatBeca#13]
Hi @fashberg 
Do you have any idea why the HA graph is scattered? There should be a blue line with the desired temperature (as it was before), but now it shows up only on several places. This is the same on both of my thermostats since I updated from v1.00 to v1.11-fas. 
![Képkivágásgraph](https://user-images.githubusercontent.com/48806033/81915114-136c0480-95ca-11ea-8987-9f9d6bad0f0b.JPG)

**Comment by fashberg** [comment]
Hey @iMike78 .

Do you use HA Autodiscover?
Looks like issue #11 - which is fixed in 1.12-fas.

**Comment by austwhite** [comment]
This issue is 100% fixed in 1.12-fas

**Comment by iMike78** [comment]
I just updated to v1.12-fas, and I'm testing now, thank you!
