### ISSUE TITLE
HA autodiscovery not working.

### ISSUE THREAD

**Issue by stav242** [fashberg/WThermostatBeca#131]
i have a BHT-002GALW, configured with firmware WThermostat 1.19.beta1-fas (i have also tried the previous 1.18 version) . 

I can see mqtt messages, but the thermostat is not being auto-discovered in HA using mqtt.

do you have any suggested troubleshooting i can do ?

**Comment by jorch17b** [comment]
@stav242 have you solved the problem?

**Comment by stav242** [comment]
Yes. Although can't pin down exactly which of the changes made it work.
Think it was my mqtt broker auto discovery setting that wasn't working. I
reinstalled the mqtt broker and reset all the config for it.

**Comment by stav242** [comment]
On a side note....

I think I had a problem with the thermostat name having a # symbol in it.  I'll see if i can replicate it again.
