### ISSUE TITLE
Cant set min_temp & max_temp for home assistant auto discovery

### ISSUE THREAD

**Issue by bensuffolk** [fashberg/WThermostatBeca#132]
I would like to set a different range for my temperature settings than is currently being sent via MQTT on auto discovery. They are currently set at 10 and 35, but I would like an option to be able to go down to 5 so I can set a low temperature for I'm not here but don't want anything to freeze whilst I'm away sort of thing.

I have tried changing the setting under developer tools on HASS but it seems to revert back to the preset min of 10 shortly after. Presumably when it gets a new auto discovery message.

**Comment by MrR-tm** [comment]
Webui > configure thermostat >  uncheck switch back to auto mode from manual at next schedule period change?

**Comment by bensuffolk** [comment]
> Webui > configure thermostat > uncheck switch back to auto mode from manual at next schedule period change?

That was not the issues. In the mqtt auto discovery message it sets the min and max temp values. These are 10 and 35 in the version I am using 1.18-fas 

Is it worth upgrading to a new version to help address this?

**Comment by MrR-tm** [comment]
Apologies, I don't keep an eye on github like I should. 

Personally I have moved to esphome, it's more stable than this and the other firmware's available on which I had constant drop outs and the latest fas firmware just stopped responding to requests from HA along with even more drop outs, esphome is at least always available!

This means I now have to use Node-RED to automate certain aspects of my heating as it can't access the schedule of the thermostat which is annoying but realistically it's forced me to set up some of the automations that i wanted to implement for my heating via Node-RED.
