### ISSUE TITLE
cannot set target temperature MQTT in iobroker

### ISSUE THREAD

**Issue by reutli** [fashberg/WThermostatBeca#135]
I set up the mqtt-server in iobroker and I'm able to read alle the values & states.
But I'm not able to set a target temperature. If I do so, this has no effect against the device and will be overwritten after a few second.

So how should I'm able to set the desired temperature via iobroker?

**Comment by ATBERKDA** [comment]
I‘ve the same issue but no solution until now. Tested with SonoffMQTT and MQTT-Server plug-in

**Comment by langsoftware** [comment]
I have also the same issue, will this issue be fixed soon?

**Comment by Bettman66** [comment]
This can be done without any problems in ioBroker, you only have to create an object yourself.
Example:
Wohnzimmer/stat/things/thermostat/properties/targetTemperature
Set:
Wohnzimmer.cmnd.things.thermostat.properties.targetTemperature
