### ISSUE TITLE
HA Autodiscovery not working

### ISSUE THREAD

**Issue by giovi321** [fashberg/WThermostatBeca#141]
I'm not sure what I am doing wrong but HA auto discovery is not working at all. What are the steps to follow to enable it? Maybe I'm missing something.

**Comment by paulius2k** [comment]
> I'm not sure what I am doing wrong but HA auto discovery is not working at all. What are the steps to follow to enable it? Maybe I'm missing something.

Have you followed _everything_ listed here?:
https://github.com/fashberg/WThermostatBeca#hass-autodiscovery

You have to see your new device in HA Configuration-->Integrations under the MQTT integration:
<img src="https://user-images.githubusercontent.com/24705262/147883172-f7828493-fc45-4e5b-bb32-8db543b9943f.png" width="30%">

**Comment by pfunkowski** [comment]
i have similar problem, finally problem is in mqtt password - firmware limit password length to 10 characters... standard mosquito password is too long ...
can You try
homeassistant > configuration >addin > mosquitto broker > configuration and add login like:

logins:
  - username: user
    password: passwd

restart mqtt broker and use Your new login in thermostat
