### ISSUE TITLE
ME81H problems

### ISSUE THREAD

**Issue by jaovaskainen** [fashberg/WThermostatBeca#158]
Hi

I´m facing some problems when trying to integrate Avatto ME81H thermostat into home assistant. 

I´ve flashed my thermostat by soldering wires to TYWE3S and using Tasmotizer. Flashing was successful and I managed to do the configuration to the point where thermostat is visible in my local network and I´m able to use the thermostat web interface and also verify that auto discovery in HA is working. But then comes issues.

1. From thermostat web interface info window I can see that each time I reboot the thermostat, MCU won´t auto-initialize. I guess that´s not intentional? 

![image](https://user-images.githubusercontent.com/111431615/190874127-7424b268-9537-42ce-9aff-2c90b9d9957d.png)

2. After manual initialization from web interface everything else seems quite correct, but current temperature and target temperature are both zero.

![image](https://user-images.githubusercontent.com/111431615/190874253-a4539bfe-a006-4c2e-a546-d37ee040624b.png)

3. Like being said, auto discovery in HA is working, but controlling the thermostat from HA is acting weird. Obviously HA thermostat card is not showing current temperature and target temperature due to problem with those already in thermostat web interface, but that´s not all. 

![image](https://user-images.githubusercontent.com/111431615/190874570-e27a6544-3694-41f8-b0ae-e756602a715b.png)

- When pressing HA interface power icon it shuts thermostat down. That´s good I guess. Pressing it again won´t fire it back up. Not good I guess.
- When power is off and flame icon is pressed thermostat is fired back up.
-  Using the slider which is supposed to be used when changing target temperature is actually changing thermostat into a schedule mode. And there´s no way to change it back from HA interface. 

Here´s also a screenshot of WebLog from thermostat web interface.

![image](https://user-images.githubusercontent.com/111431615/190874753-d2db59bf-8147-4d84-a2ec-2b8fee2da679.png)

Those "Warning : MCU : Unknown; ........." lines are also visible in mqtt traffic. 

So it seems to me that my configuration and mqtt communication is working fine but there´s something wrong in communication between TYWE3S and MCU. 

Is this something that´s well known issue and easily fixed or do I just have to dump these thermostats? Or at least dump the idea of controlling them with HA.

I understand that this is not propably tested or intented to be used with ME81H, but according to some conversations people have been able to get it up and running with this hardware too.

Please let me know if any additional info is needed.

**Comment by fashberg** [comment]
Hey!

ME81H is not supported yet. It has a similar, but not the same protocol.
Feel free to PR

Folke
