### ISSUE TITLE
Unable to flash BHT-6000 with CH340G 

### ISSUE THREAD

**Issue by borkie** [fashberg/WThermostatBeca#159]
Hi, has anyone been successful in flashing the thermostat BHT-600 (the round one) in question with CH340G adapter?
esptool always report this error:

`A fatal error occurred: Failed to connect to Espressif device: No serial data received`

I've tried a lot of time, with different baud, but without success.
I cabled the TYWE3S like this pic https://github.com/fashberg/WThermostatBeca/blob/master/Flashing.md#22-connection-to-device-for-flashing

Has anyone had the same problem? how did you solve?

**Comment by jj-uk** [comment]
Have you tried to flash the device with a different serial adaptor? Or are you able to supply the device with 3v3 externally (e.g. not from the serial adaptor) ?
Serial adaptors cannot supply much current and may not be able to power the circuity resulting in a failed flash.

**Comment by catdogmaus** [comment]
I was successful only with unsoldering and soldering chip back after flashing. But I was in situation where the previous flash did not work and I needed to do it directly. If u still have OEM software on BHT-6000 u can use OTA with tuya convert. I have also done that successfully
