### ISSUE TITLE
Temperature values are wrong

### ISSUE THREAD

**Issue by pozzeco** [fashberg/WThermostatBeca#160]
Hello,

real temperature in Tuya app are 21.5 °C and set temp. are 22.5 °C.
In HA 4.3 °C and 4.5 °C.
Why? It was fine with some old repository version.
Thermostat BHT-002-GBLW WiFi

![Screenshot_2022-10-03-18-37-05-997_com tuya smart](https://user-images.githubusercontent.com/77241037/193619311-9b7f5c3f-b543-4eb2-abbe-4ad7118d1782.jpg)
![IMG_20221003_183728](https://user-images.githubusercontent.com/77241037/193619316-5e3a169f-63d7-43c8-b28e-c7d51bb37b37.jpg)

**Comment by leoshusar** [comment]
Are you using the official Tuya integration? If so, don't bother, it's broken and Tuya doesn't care.
