### ISSUE TITLE
Wifi password length limited to 32 characters

### ISSUE THREAD

**Issue by timeo-78** [fashberg/WThermostatBeca#164]
According to IEEE 802.11i the WPA PSK length should have a maximum of 63 characters.
Please enable full password length to get compliant to standard.

Version [Release v1.22-fas](https://github.com/fashberg/WThermostatBeca/releases/tag/v1.22-fas)

**Comment by fashberg** [comment]
Hey,

currently not possible, due to low memory. You can compile your own fw, but then all settings will be lost, because the memory/settings layout will change then
