### ISSUE TITLE
Accuracy of MCU built in controller on BHT002

### ISSUE THREAD

**Issue by Funkenschuhster** [fashberg/WThermostatBeca#166]
The accuracy of the MCU seems to be a two-possition controller with a hysteresis of +/-0.5K. But for my case thats not a good controller setup. My floor heating takes 4-6h to heat up/cool down. So at setpoint of 22°C I cycle around 20.5 to 23°C.
A PI controller with PWM would be better choice, like tasmota thermostat. But I know thats in the hand of the MCU.
Is there any documentation about the MCU and may a way to flash it? Would be nice, if the control is done by ESP and MCU manages only relay and display.

**Comment by roesl** [comment]
I have the same problem - with setpoint 20 the temp cycle around 18 to 22 - this ist unusable for floor heating.
Is it possible to get the temperature from an external sensor, because the internal sensor will be heated from the Thrermostat itself and measures the case temperature and not the room temperature

**Comment by juhjar** [comment]
Yes, hysteresis and sensor offset is needed. 

In my case, there is 1,5deg difference between mounted or hanging on cable. Moving sensor outside of casing could help, but offset would be accurate enough.


![IMG_20230115_124959_151](https://user-images.githubusercontent.com/39704135/212536580-a8665e5a-03c3-41a0-a2b5-5d537affb529.jpg)

**Comment by Funkenschuhster** [comment]
You can Set an offset by pressing and hold the "Windows" key and clock for
5 seconds. Then change parameter 1.

Sent from my mobile device / Von meinem Mobilgerät gesendet

juhjar ***@***.***> schrieb am So., 15. Jan. 2023, 11:56:

**Comment by roesl** [comment]
Hello, How to change hysteresis? --Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.Am 15.01.23, 13:24 schrieb Funkenschuhster ***@***.***>:

   You can Set an offset by pressing and hold the "Windows" key and clock for
   5 seconds. Then change parameter 1.
   
   Sent from my mobile device / Von meinem Mobilgerät gesendet
   
   juhjar ***@***.***> schrieb am So., 15. Jan. 2023, 11:56:

**Comment by kirscheGIT** [comment]
This should be parameter 2
![051AE15D-10E0-4EBB-B8F7-DAD60503654A](https://user-images.githubusercontent.com/45150988/212543905-02168fc1-f1d5-4684-bdc5-d0c6d43009f4.png)

**Comment by roesl** [comment]
Thanks, but I would need a lower hysteresis than 1--Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.Am 15.01.23, 14:36 schrieb kirscheGIT ***@***.***>:

   
  This should be parameter 2

**Comment by kirscheGIT** [comment]
Better than 1? Looking at the behavior of my Beca, 1 means the hysteris span. 
So when you set the thermostat to 20 it will stop heating at 20.5 and start heating at 19.5. 
Better resolution can‘t be achieved as the measurement and set step size is only 0.5

**Comment by juhjar** [comment]
Hmm, even I moved thermistor outside of casing... there is still 1,5deg difference on measurement, between mounted/hanging. Maybe power supply keeps casing too warm and room has to cool down a lot compared to setpoint, which makes it feel like hysteresis is too big.

On picture you can see two times when I let thermostat to hang on it's cable and mount it back. Could some one verify this too? Next I will drill some air vents on top of casing,


![image](https://user-images.githubusercontent.com/39704135/212551228-8d21d8f1-3176-4658-8ba2-26b5d8d84376.png)

**Comment by roesl** [comment]
I also moved the thermistor out of casing, and this works much better. The internal electronic sometimes heats the thermistor, so the difference between real room temperature and measured temperature is sometimes more than 3 when there is no ventilation when nobody is at home and then its cold when coming home 😭--Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.Am 15.01.23, 16:55 schrieb juhjar ***@***.***>:

   
  Hmm, even I moved thermistor outside of casing... there is still 1,5deg difference on measurement, between mounted/hanging. Maybe power supply keeps casing too warm and room has to cool down a lot compared to setpoint, which makes it feel like hysteresis is too big. 
  On picture you can see two times when I let thermostat to hang on it's cable and mount it back. Could some one verify this too? Next I will drill some air vents on top of casing,

**Comment by kirscheGIT** [comment]
On my Beca it sits here and it works well enough for me.

![AE91E046-BD7D-416F-96E9-816E03227279](https://user-images.githubusercontent.com/45150988/212552685-c559bc45-df05-4942-a579-94d227319a1c.jpeg)

What you could do, is to have a separate thermometer in the room and use this value to manipulate the set temperature and turn the thermostat on and off. This can be done with openHAB at example.

**Comment by jwillmer** [comment]
> What you could do, is to have a separate thermometer in the room and use this value to manipulate the set temperature and turn the thermostat on and off. This can be done with openHAB at example.

I already asked for something like this: https://github.com/fashberg/WThermostatBeca/issues/173
