### ISSUE TITLE
BHT-002 GALW not able to backup the firmware

### ISSUE THREAD

**Issue by roesl** [fashberg/WThermostatBeca#169]
Hello,

I bougt a MOES BHT-002 GALW and when I connet to USB and use an extra voltage regulator with 3,3 V connected to USB 5V there drops the voltage down to 3,1 V and the supply voltage LED flickers. 
When I use an external powersupply with 2,5 A the power is stable.
But in both cases thers is no connection from esptool to the chip  when i want to do a backup.
So I dont want to try to flash the chip. 
Maybe there is a problem, because the RX and TX are connected to the MCU ?

Does anybody have the same problem with the newer versions of the BHT ?

**Comment by MellotronScratch** [comment]
I had a similar problem. I wasn't able to connect to the chip so I desoldered it and connected it to my SH-UD9C2 with jumper wires. I connected the RTS from the  adapter to RST from the chip so it automatically resets when reading/flashing. Without connecting tot RST I wasn't able to.
