### ISSUE TITLE
Direct MQTT relay activation

### ISSUE THREAD

**Issue by cjgarciao** [fashberg/WThermostatBeca#170]
Hello,
I need to activate the thermostat relay directly via MQTT, is this possible?
Thank you,
Carlos.

**Comment by fashberg** [comment]
As described here: https://github.com/fashberg/WThermostatBeca#can-you-add-xxx-as-a-feature
Answer: no

The wifi module cannot control the relay.
But just set to manual mode and a high enough target temperature
