### ISSUE TITLE
MOES BHT-002GBLW now with CB3S

### ISSUE THREAD

**Issue by mini-mi** [fashberg/WThermostatBeca#171]
Hi,

i bought 4 BHT-002GBLW from MOES and have the problem that they are now using the new CB3S chip.
So it is not possible to use this anymore or am i wrong?

I try to buy other and hope to get some with the old chip or try to change the chip.

Regards

Max

**Comment by rande83** [comment]
Hi.

It is still possible with soldering skills....

I replaced the CB3S with an ESP-12S.

**Comment by btk999** [comment]
> Hi.
> 
> It is still possible with soldering skills....
> 
> I replaced the CB3S with an ESP-12S.

is this a 1:1 replacement of the chip or are there any other things necessary?

**Comment by rande83** [comment]
> > Hi.
> > 
> > It is still possible with soldering skills....
> > 
> > I replaced the CB3S with an ESP-12S.
> 
> is this a 1:1 replacement of the chip or are there any other things necessary?

Hi.

Yes the ESP-12S is 1:1 compatible.

With other ESP boards you may have problems booting, even if the pinout is identical. This is because certain pins still need a pull up and pull down resistor.

So better take the ESP-12S directly, flash it before soldering and then replace the CB3S with it.

Small hint: When soldering better remove the PCB from the display, otherwise you will get permanent black spots on the display due to the heat.

**Comment by btk999** [comment]
> 
> Hi.
> 
> Yes the ESP-12S is 1:1 compatible.
> 
> With other ESP boards you may have problems booting, even if the pinout is identical. This is because certain pins still need a pull up and pull down resistor.
> 
> So better take the ESP-12S directly, flash it before soldering and then replace the CB3S with it.
> 
> Small hint: When soldering better remove the PCB from the display, otherwise you will get permanent black spots on the display due to the heat.

Thanks! So no additional shortage Connections necessary. Im gonna try it :)

**Comment by rande83** [comment]
> 
> Thanks! So no additional shortage Connections necessary. Im gonna try it :)

No.
Only if you want to do the hardware hack to connect the heating relay to gpio5.

**Comment by btk999** [comment]
What is the advantage oder that?

**Comment by rande83** [comment]
> What is the advantage oder that?


The advantage is that u can see the real status of the heating relay in the web interface and via MQTT, I guess. 

![Screenshot_20230102-121810_Edge~2.png](https://user-images.githubusercontent.com/62604250/210225166-6cf839ac-c141-4e6e-a69f-41efba4c4769.png)

**Comment by btk999** [comment]
Thanks! I searched for it but i could Not find further information, is Thais documentated somewhere?

**Comment by rande83** [comment]
> Thanks! I searched for it but i could Not find further information, is Thais documentated somewhere?

![Screenshot_20230102-123346_GitHub.png](https://user-images.githubusercontent.com/62604250/210226070-f18902b5-1cf3-44dd-af9d-8cb730ea718c.png)

It is mentioned in the configuration.md

And further in this link: https://github.com/klausahrenberg/WThermostatBeca/issues/17

**Comment by mini-mi** [comment]
I can confirm it works with this ESP-12F

https://www.amazon.de/gp/product/B0B143QLPW/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1

And I also recomment to work careful and slowly otherwise you can damage the display, but 3/4 worked well.

**Comment by timeo-78** [comment]
Did anyone check if the BHT-002 GB B (without wifi) has the same PCB without the ESP module? In this case it would be easy to add ESP-12S or ESP-12F without unsoldering the CB3S chip. Just a thought I have, wondering if someone already checked it.
