### ISSUE TITLE
Disable LED ring

### ISSUE THREAD

**Issue by bruestel** [fashberg/WThermostatBeca#177]
Is it actually possible to disable the LED ring on my BHT-002. Unfortunately, I couldn't find a way to do this on the web or in the source code. Before I settle for that, I wanted to at least ask if anyone has any ideas.
Alternatively, I could try to cover or unsolder the LED.

![2022-12-30 08 14 52](https://user-images.githubusercontent.com/2088078/210044511-90a26a5d-9933-4b61-ac7e-a60a43709093.jpg)

**Comment by fashberg** [comment]
As described here: https://github.com/fashberg/WThermostatBeca#can-you-add-xxx-as-a-feature
Answer: no
