### ISSUE TITLE
Where to buy devices with esp chipset?

### ISSUE THREAD

**Issue by btk999** [fashberg/WThermostatBeca#178]
Hi guys,

i ordered some devices at aliexpress / amazon, but all of them have incompatible chips and i dont want to solder.
Does somebody know a good shop/source that sells devices compatible to WThermostatBeca with esp8266 chip?

Thanks and regards

**Comment by Trashmee** [comment]
https://github.com/klausahrenberg/WThermostatBeca/issues/290

**Comment by malgates** [comment]
Found the same. 	
BecaSmart Serie 6000 still seem to come with esps.
