### ISSUE TITLE
AP Wifi Password

### ISSUE THREAD

**Issue by thundergreen** [fashberg/WThermostatBeca#18]
Helo I flashed with tuya method. So far so good but I have now an AP Thermostat-Beca_xxxx and it asks me for a password to connnect. YOuld you mind telling me what password it is?

Thanks in advance

**Comment by fashberg** [comment]
Hi @thundergreen 

have you tried 12345678   ?

Documented here: https://github.com/fashberg/WThermostatBeca/blob/master/Configuration.md

Kind Regards
Folke

**Comment by thundergreen** [comment]
Please ignre this unrelevant stupid question :)
