### ISSUE TITLE
BHT-002-GALW - power button always red?

### ISSUE THREAD

**Issue by Trashmee** [fashberg/WThermostatBeca#180]
Hi,

I'd be very happy to get advices - this is a friendly plea for community support, not an issue :-)

> BHT-002-GALW has the power button lightning red at all times  
https://github.com/klausahrenberg/WThermostatBeca/issues/291  

Thanks,
Alex

**Comment by bruestel** [comment]
I think this "issue" is related to https://github.com/fashberg/WThermostatBeca/issues/177

**Comment by fashberg** [comment]
As described here: https://github.com/fashberg/WThermostatBeca#can-you-add-xxx-as-a-feature
Answer: no
