### ISSUE TITLE
Cat access the gui after first setup.

### ISSUE THREAD

**Issue by sasaderer** [fashberg/WThermostatBeca#181]
Hi!

After flashing the ME81H device I was able to access the gui - I entered my Wifi network and MQTT broker info.
It connected to wifi and it is sending some data to mqtt broker, but when I access the device with web browser, the "root page" does not show the GUI anymore but instead this: 

![image](https://user-images.githubusercontent.com/121898907/210552748-9c32ae47-b20f-4af4-a4af-59646c00755e.png)
Is it possible somehow to access the GUI again, reset or flash the device via MQTT commands?

Br

**Comment by kirscheGIT** [comment]
Append /config? to the ip in the browser.

**Comment by sasaderer** [comment]
Wow - so it was that simple - I do see the GUI there:)
Thank you!
