### ISSUE TITLE
Question: Additional sensors

### ISSUE THREAD

**Issue by jwillmer** [fashberg/WThermostatBeca#183]
I would like to report the humidity in the bathroom as well and the case seams to have enough space to add an additional sensor. From the hardware side I don't see a problem but I don't know enough about the software. How easy is it to add support for an additional sensor? 

Note: Since the device is always on and on the mains it is perfect to add additional sensors. I could also think of a light sensor or maybe a movement sensor - sure not all at once but depending on the location one of them could make a lot of sense.

**Comment by malgates** [comment]
I would absolutely love that as well!
