### ISSUE TITLE
Tuya/Beca BHT-1000 Thermostat works perfectly, even the Hardware hack

### ISSUE THREAD

**Issue by hakspiel** [fashberg/WThermostatBeca#187]
I tried my luck with a newly purchased Beca BHT-1000 (Production 07/2022).

I replaced the original CB3S WiFi Modul with an ESP8266-12F .
That is a 1:1 replacement, Pin Compatible.

What shall i say, everything works on the first try.

Hardware hack also works.

I am happy, thank you for your Project!

Original BHT-1000:
![IMG_6517](https://user-images.githubusercontent.com/47637952/214823665-f41abbbf-8a94-49f3-83b0-da3f417e6bb1.jpg)

With replaced ESP-12F Module:
![IMG_6518](https://user-images.githubusercontent.com/47637952/214823987-364d5a7e-6fde-46d5-9485-4d11bce30019.jpg)

With Hardware-Hack (next one will look better, but works):
![IMG_6519](https://user-images.githubusercontent.com/47637952/214824027-f8061298-4691-46b9-ae57-81ac5c99eafc.jpg)

**Comment by malgates** [comment]
Nice one! What does the Hardwarehack do?

**Comment by hakspiel** [comment]
The problem without Hardware hack is that you cannot detect the relais position. There is only an assumption available. 

The hardware hack connects the 5v output (that drives the relais) to the input of the ESP (you need the voltage devider otherwise ESP might be grilled with 5V). 
Now the ESP can directly detect the position of the relais. 

This is implemented in the Software, selectable via dropdown Menu in the configuration.
