### ISSUE TITLE
Cyclic reboot

### ISSUE THREAD

**Issue by Alaric84** [fashberg/WThermostatBeca#189]
Hey, after flashing everything seems to work.
Wifi, WebView, MQTT.
Without interaction I have a Cyclic reboot about every 2 minutes. 
Log does not show anything. Just connection lost and then it comes up again.

Does anyone have any hints?

**Comment by poseidogithub** [comment]
Same problem here buddy, I have 3 thermostars that dont go past the 5 minutes uptime ever. they jusr reboot by themselves, as an aditional symptom, when they do, sometimes cant connect to the mqtt server. both in 1.22 and 1.23beta versions
on weblog I cant's see hte reason 
(mqtt log is useless as they reboot and until connect there is no new info)

I'll open an issue
