### ISSUE TITLE
Web UI nit accessible any more

### ISSUE THREAD

**Issue by eisengrau** [fashberg/WThermostatBeca#203]
Hello,

I did the mistake of flashing Klaus-Ahrenberg's version (I had 1.22-fas) on one of my BHT-002s. I flashed back to 1.22-fas. Network settings were preserved, however I am not able to access the web interface any more, looks like the web server does not respond any more.

I did the recovery by holding the down button and connecting to the device AP, there the Web GUI was working. I also flashed a minimal image (1.19-fas minimal) as I read as an interim solution coming from the Klaus-Ahrenberg version. Issue is same, device connects to my WiFi network, MQTT also working but no web GUI any more. Also with the minimal version, looks like there is no possiblilty to hold down button to get to the recovery AP mode.

Do I need to reflash the ESP module via serial so I can get back the funtioning Web UI?

**Comment by fashberg** [comment]
Yes, probably Settings are broken now and app crashes during load.
Resetting via serial is then the only chance

**Comment by Stoatwblr** [comment]
For reference, the webui on Klaus-Ahrenberg's version is on [ip.of.un.it]/config (the base URL provides a Mozilla Webthings interface)

Folke, is there any chance of you and Klaus merging changes?

**Comment by lee-js** [comment]
I'm in exactly the same situation, but my device has not remembered the network settings and just gives "Err" when trying to enter the AP mode by holding the down button.
Is there any other way to do this?
