### ISSUE TITLE
WGA-006-WH-MS  supported?

### ISSUE THREAD

**Issue by sweti3** [fashberg/WThermostatBeca#206]
Hi,

there are new thermostats that look quite awesome: WGA-006-WH-MS 

https://www.amazon.de/MOES-Fussbodenheizung-Programmierbar-Heizungsthermostat-Sprachsteuerung/dp/B0B3SX18NR/ref=sr_1_2_sspa?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=155XNEX0RXUJ4&keywords=moes%2Bthermostat&qid=1691488365&s=diy&sprefix=moes%2Bthermosta%2Cdiy%2C101&sr=1-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1

Is the Firmware flash also possible here? Or not so much? Thanks a lot in advance!

**Comment by fanatic1** [comment]
Did you try to flash it? I have the same from your link and I'm wondering if it will work....
