### ISSUE TITLE
CB3S BK7231N

### ISSUE THREAD

**Issue by tomik671108** [fashberg/WThermostatBeca#208]
Hi.
I purchased BHT-002-GCLW and I have a problem communicating with it.

```
tomik67@tomik67MINT ~ $ esptool -p /dev/ttyUSB0 -b 460800 read_flash 0x00000 0x100000 originalFirmware1M.bin
esptool.py v2.8
Serial port /dev/ttyUSB0
Connecting........_____....._____....._____....._____....._____....._____....._____
A fatal error occurred: Failed to connect to Espressif device: Timed out waiting for packet content

```
Inside there is a different CB3S module than yours with the BK7231N chip.

[https://developer.tuya.com/en/docs/iot/cb3s?id=Kai94mec0s076](url)

Does anyone have experience with such a case?

**Comment by openshwprojects** [comment]
[OpenBeken](https://github.com/openshwprojects/OpenBK7231T_App) runs on BK7231 (and BL602, and W800, and W600, and more..) and supports TuyaMCU well in a scriptable and customizable manner, we can also have custom pages [hosted on OBK LittleFS](https://www.elektroda.com/rtvforum/topic3971355.html), so it should be possible to support it easily.

**Comment by Kihltech** [comment]
I have an BHT-002GALW-W / BHT-002-GALW with this CB3S chip, which I'm interested in flashing to this firmware. 
From what I understand I'm not able to directly use the current firmware. 
I have a suitable ESP programmer and I can attempt to extract the firmware if that can be usable. I'm also willing to donate one unit to help with the reverse engineering. 

Here's a picture of the unit:
![20231223_155035](https://github.com/fashberg/WThermostatBeca/assets/6899243/3a26ab07-bb15-4907-bebb-d2f9bcb6e48a)

For future reference, I believe two resistors need to be removed to allow flashing:
https://www.elektroda.com/rtvforum/topic4003974.html

**Comment by tomik671108** [comment]
Hi.
The latest TUYA devices are equipped with Beken chips, which cannot be loaded with Tasmota, only OpenBK.
Read this entire thread (and others about OpenBK):
[https://www.elektroda.com/rtvforum/topic4003974.html](url)
, see if you are able to backup the original firmware first and then flash OpenBK.
Instructions are in the thread.
Indeed, resistors Q1 and Q2 need to be desoldered during the first upload of OpenBK, later updates are OnAir.
At the same time, you can add an additional connection that will allow you to obtain information about the actual status of the relay.
When you are ready, I will show you my thermostat configuration in Home Assistant, and help you with the first configuration of OpenBK.

**Comment by paravoid** [comment]
For what it's worth, besides OpenBK, you can nowadays flash the Beken chips with ESPHome.

I have a working config here:
https://devices.esphome.io/devices/Beca-Thermostat

Note that I did not have to desolder anything to flash, everything just worked.
