### ISSUE TITLE
Support for Avatto WT200 electric floor heating thermostat

### ISSUE THREAD

**Issue by andreas-bulling** [fashberg/WThermostatBeca#209]
It would be fantastic if there was support for the [Avatto WT200 electric floor heating thermostat](https://de.aliexpress.com/item/1005005104774576.html?spm=a2g0o.home.0.0.22e712e2GB7krD&mp=1&gatewayAdapt=glo2deu) - this device is the only one I could find that fits into the the standard 55mm frames.

**Comment by andreas-bulling** [comment]
it seems I am the only one interested in support for this thermostat...

**Comment by kirscheGIT** [comment]
Saw this right now. Could be interesting for retrofitting my Halmburger Thermostats. 
So I’m interested. 
do you know what type of NTC they are using?

**Comment by andreas-bulling** [comment]
I am afraid not - but I have a spare one laying around. Which chip should I look out for? I could also take a picture of the whole PCB...

**Comment by kirscheGIT** [comment]
Usually it is somewhere stated close to the sensor terminal blocks on the housing, in the manual or on the sensor itself. If you don't find it there, than you could just measure the resistance of the NTC with a multimeter. When you know the room temperature it should give a hint to the nominal NTC type. 
The BECA Thermostats have a 10k Ohms NTC, I think

**Comment by andreas-bulling** [comment]
NTC3950 10k

**Comment by kirscheGIT** [comment]
> NTC3950 10k

Thanks! Then I need to think about some kind of adaption. Nevertheless, if somebody would implement the support for this I would be very happy!

**Comment by kirscheGIT** [comment]
BTW. could you take some pictures of the PCB.? Maybe this helps that someone in here can say how good the chances are that this thing could be working.

**Comment by MaciejKucia** [comment]
The WT200-16A-W without a relay module. The main MCU is CMS8S5887

![20240110_184724](https://github.com/fashberg/WThermostatBeca/assets/2974328/10e24a5b-9f23-40fd-aaca-c385ffbafffe)
![20240110_185528](https://github.com/fashberg/WThermostatBeca/assets/2974328/24eb2978-1abf-4cb1-8e32-eb6288dcc172)

I am afraid to remove the metal frame as it most likely would damage the hard plastic housing.

**Comment by kirscheGIT** [comment]
Hi, 
thanks for the pictures. 
I was a little bit impatient and ordered one on Monday from amazon. And it arrived today

So here are my pictures. BTW:
The metal frame remains in the outer plastic frame. The small white plastic clips of the inner frames can be pushed easily and the inner frame incl. the electronics come out of the front.

![IMG_6342](https://github.com/fashberg/WThermostatBeca/assets/45150988/2500f6e5-c739-4ba5-9127-f02919e84edd)

![IMG_6343](https://github.com/fashberg/WThermostatBeca/assets/45150988/8898bd7c-fca0-46d6-95a5-3d80ecd13c8d)

![IMG_6341](https://github.com/fashberg/WThermostatBeca/assets/45150988/1582836b-9c58-4556-9d66-2b182a93e83a)


![IMG_6335](https://github.com/fashberg/WThermostatBeca/assets/45150988/2d206b15-2653-4a54-9556-2adab76d5790)

![IMG_6336](https://github.com/fashberg/WThermostatBeca/assets/45150988/3b19a88d-9d31-4954-afd1-1e6d4b64c707)

The design itself seems to run completely with 3.3V.
What makes a little headache is the WBR3 module. A brain transplantation has to be made with an ESP-12. This can be a little bit tricky, as the whole PCB is much smaller as the BECA at example.


For me it was interesting if I could reuse the floor NTC. As the measurement is very simple the answer is yes. It is just a simple voltage divider with a capacitor in parallel. R7 is the top resistor and C4 is the capacitor. 
When modifying the top resistor according to the NTC nominal value, this might work. For sure this depends on the resistor. So you have to use some correction factors when you use it in your home automation.

![IMG_6338](https://github.com/fashberg/WThermostatBeca/assets/45150988/71fa5dd5-42e1-4685-b747-6dd618044eff)

I made an example calculation based on a 2k NTC (when using dark mode click on the picture to see the calculations):

![image](https://github.com/fashberg/WThermostatBeca/assets/45150988/e7d4dc41-bfd4-43d3-8497-90812485b8dd)

Two warnings:
1. The system has a safety feature which prevents the floor from overheating. In our case the shutdown will happen 7°K later. This could be mitigated by using a 2k2 resistor as top resistor. But this makes the readings of the lower values worse
2. If you have a NTC/ voltage divider with a lower resistance, then the current flowing through the NTC is higher, causing more self heating

So from the looks of it, the HW can be made compatible. However, my guess is that the protocol between the CMS8S5887 and the Wifi module is different from the others. So some SW adjustments have to be made. 

Regards,

Chris
