### ISSUE TITLE
Feature request: automatically turn on the thermostat when connected to power

### ISSUE THREAD

**Issue by giovi321** [fashberg/WThermostatBeca#226]
Hi,
the BHT-6000 does not automatically turn on when power is given to it. It would be nice to have the option to turn on automatically the device when power is given to it, the equivalent of sending an mqtt message like this:
```
topic: thermostat1/cmnd/things/thermostat/properties/deviceOn
message: true
```

Currently I'm managing it through home-assistant sending this message with a schedule, but it would be nice for the thermostat to be independent.

Thanks!

**Comment by Stoatwblr** [comment]
Are you sure about that? At least some of these devices have this option in the presets (resume, off, on)

**Comment by giovi321** [comment]
I'm quite sure... where should I see this option? Sending a MQTT message?

**Comment by tomik671108** [comment]
I would also be interested in such a function, remembering the state before the power failure would be very helpful.

**Comment by giovi321** [comment]
I checked, there's no preset {resume, off, on}.

`{"idx":"therm_1piano","ip":"192.168.165.156","firmware":"v1.22-fas","switchBackToAuto":false,"temperature":17.50,"targetTemperature":5.00,"deviceOn":true,"schedulesMode":"off","holdState":"manual","ecoMode":false,"locked":false,"mode":"heat","preset":"none","action":"idle","state":"off","mcuId":"IAYz2WK1th0cMLmL1.0.0"}`

Would really appreciate if you could integrate that, I don't know how hard it is though :)
