### ISSUE TITLE
Support for external 6.8Kohm temperature sensor

### ISSUE THREAD

**Issue by loony82361** [fashberg/WThermostatBeca#23]
Hello! Is it possible to add support for an external temperature sensor with a resistance of 6.8 kOhm in the firmware? This sensor has remained from the old thermostat and is walled up in the floor; replacing it with a standard one is very problematic. Thank!

**Comment by fashberg** [comment]
Hey @loony82361,

as you can read in https://github.com/fashberg/WThermostatBeca#hardware WThermostat replaces only the WiFi modules firmware.

Temperature measuring, reaction to temperature (relay control), etc. is controlled by MCU Chip and we have to use it as it is.

So no chance! sorry.

For testing i had ordered this one: https://www.amazon.de/gp/product/B01EZZS76E
Worked great.
Or 5 pieces for 8 EUR https://www.amazon.de/Aussel-Waterproof-Digital-Thermal-Temperature/dp/B01LL9JFIG/ 

Kind Regards

Folke
