### ISSUE TITLE
Syslog support for logging

### ISSUE THREAD

**Issue by Bl00d-B0b** [fashberg/WThermostatBeca#30]
Hello,

I assume it should be easy to add syslog support for logging?

Ed

**Comment by fashberg** [comment]
Hi @Bl00d-B0b 

is just
``` mosquitto_sub -h mqtt -t 'home/therm-test1/tele/log' -v```
Is it not suitable for you? You can also log this to file. 
Mosquitto cannot log values to logfile, so you have to get messages using mqtt.
Adding syslog also means adding more config-values (syslog-server, port, etc.)
I will not overblow the device.
Except someone else want's to add.

Kind Regads
Folke
