### ISSUE TITLE
How to run temperature calibration

### ISSUE THREAD

**Issue by nimda5** [fashberg/WThermostatBeca#33]
It's not a your firmware problem, just maybe you know.

Got another thermostat installed. And room temperature display wrong totally. About +10c (room temp 35.5 :) )
Found in manual that something like temperature calibration have to be run, but can't find a way how do that.

Anybody know way, or device is damaged?

Update:
Found the reason. My factory temperature offset was +9. Changed it, now everything working.

![image](https://user-images.githubusercontent.com/59937948/89050349-4ddc7680-d35b-11ea-8b3e-0cc625b40620.png)

**Comment by fashberg** [comment]
Hey @nimda5,

Yes, some adjustment is neccessary. See the picture of my test-bench.
The BHT  is set to -4 (like my 'productive' ones) and the BAC is set to -2.

See also the manuals at https://github.com/fashberg/WThermostatBeca/tree/master/docs
One BHT manual shows default of -1 and the other one has default of -2.


![2020-08-02_17h07_06](https://user-images.githubusercontent.com/3075214/89126010-a25e2e00-d4e2-11ea-8867-3e2701dd02bf.png)
