### ISSUE TITLE
Change sensor to floor heating

### ISSUE THREAD

**Issue by toroff** [fashberg/WThermostatBeca#36]
Hi! How I can change sensor to floor? I need use floor sensor for thermostat and air sensor only for information in HA

**Comment by fashberg** [comment]
Hey @toroff 

check out my detailed description: https://github.com/fashberg/WThermostatBeca#external-temperature-sensor

Check out why it can't be changed: https://github.com/fashberg/WThermostatBeca/blob/master/README.md#can-you-add-xxx-as-a-feature

But: here is a great solution by IanAdd in issue #27 - he uses AL mode, so he has in HASS both values floorTemp and roomTemp and he controls Heating/Idle state with HASS by comparing floorTemp with choosen targetTemperatur.

Mode set to Heating will start to heat if chosen targetTemperature is lower then roomTemperature (MCU controlled).
If  floorTemp reaches targetTemp HASS will stop heating by set mode to idle.
