### ISSUE TITLE
PC Access point not working for tuya convert  

### ISSUE THREAD

**Issue by Dandub** [fashberg/WThermostatBeca#37]
Hi,

I was trying to follow the tuya-convert route and create an access point on my linux ubuntu. I changed the wifi interface name to the right one and no error message but the Access Point is not active.
Any help is appreciated.
Thanks,
Dan

**Comment by fashberg** [comment]
Hey @Dandub ,

seems to be very tuya specific.
As long as the tuya-convert WiFi AccessPoint (vtrust-flash) is not working (test with you smartphone) it seems to be very tuya-convert specific.

I've flashed 3 WiFi Plugs today with success using tuya-convert.
First i have  forgot "sudo" and also had the same issue. Maybe your issue?

```sh
# sudo ./install_prereq.sh 
# nano config.txt
# sudo ./start_flash.sh
```

For further support on tuya-convert please ask https://github.com/ct-Open-Source/tuya-convert/issues

Kind Regards
Folke
