### ISSUE TITLE
on off relais not reported

### ISSUE THREAD

**Issue by bwired-nl** [fashberg/WThermostatBeca#4]
Hi

your bins works very good
except 1 thing, 
if the relais switches to on, because of reaching the temp
i do not see anything changing in the mqtt massages
also with Off of course
which value should do that

properties/mode stays on "Heat" regardless of relay switch state
thanks

**Comment by Bettman66** [comment]
You need a hardware mod for it to be displayed.
[https://github.com/klausahrenberg/WThermostatBeca/issues/17](url)

**Comment by bwired-nl** [comment]
thanks id made that change, but i dont see a change... mhhh 
is it the mode field that should react

**Comment by bwired-nl** [comment]
got it hardware set hacking :-) thanks
