### ISSUE TITLE
Automatic mode doesn't report temperature

### ISSUE THREAD

**Issue by blackscreener** [fashberg/WThermostatBeca#50]
Temperature in auto mode is report from manual mode to Home Assistant. Of course RelayStateCalculation isn't work properly for automatic mode.  Also thermostat turns on heating even for 0,5 C difference when powering on by manual button.

**Comment by fashberg** [comment]
Hey @blackscreener 

should be fixed with 1.17-fas

Thanks for your feedback!

Folke

**Comment by blackscreener** [comment]
Thank you. Great work!

pon., 12 paź 2020, 23:59 użytkownik Folke <notifications@github.com>
napisał:

**Comment by blackscreener** [comment]
@fashberg 
In 1.17 auto mode switch behavior is better but arrows responsible for adjust thermostat temperature in Home Assistant changes heat mode to manual from auto only in Home Assistant.

**Comment by fashberg** [comment]
Hey @blackscreener ,

you mean that changing the temperature on the Device itself changes _not_ from scheduler to manual mode?

This behaviour can't be changed, because it's controlled by MCU! See my note on this: https://github.com/fashberg/WThermostatBeca#can-you-add-xxx-as-a-feature

Kind Regards
Folke

**Comment by blackscreener** [comment]
> 
> 
> Hey @blackscreener ,
> 
> you mean that changing the temperature on the Device itself changes _not_ from scheduler to manual mode?
> 
> This behaviour can't be changed, because it's controlled by MCU! See my note on this: https://github.com/fashberg/WThermostatBeca#can-you-add-xxx-as-a-feature
> 
> Kind Regards
> Folke

No. When thermostat is in auto mode (scheduler) and I change temperature in Home Assistant than the mode in HA changes to manual but mode in thermostats stays on scheduler.
