### ISSUE TITLE
Wifi SSID is case sensitive ?

### ISSUE THREAD

**Issue by rumoldus** [fashberg/WThermostatBeca#52]
Hi,
a low priority issue, but I discovered that Wifi SSID must match the actual case (I happen to have an uppercase SSID and entered lower case). I got it working, but it cost me some time.
Best regards
Marcel

**Comment by fashberg** [comment]
Hey @rumoldus ,

Sure, the SSID must be entered exactly. Also the WPA preshard key gets derived from SSID and secret so after changing the SSID the PSK is another one.

Do you see any mistake in the docs or software, ot just for information?


Kind regards

Folke

**Comment by rumoldus** [comment]
Hi Folke, 
As I was not used to entering SSID manually, (usually you select from a list) I was not aware of this requirement. Suggest to add a line in the configuration.md.

Marcel Payens
