### ISSUE TITLE
Wrong Single Values via MQTT

### ISSUE THREAD

**Issue by esalii** [fashberg/WThermostatBeca#53]
Hello,

single values are displayed incorrectly, regardless of what you send as cmnd/ via MQTT or set on thermostat single values deviceON,ecoMode and locked are always "true"

**Comment by esalii** [comment]
i found the failure :)
![false](https://user-images.githubusercontent.com/37306044/96189417-bd1c3c80-0f40-11eb-89a8-5c871c2cb6f7.JPG)

**Comment by Master-Rudi** [comment]
Tried your solution, but it´s not working for me. The values are still always "true"

**Comment by fashberg** [comment]
Hey @esalii ,

thanks for the Bug Report!
