### ISSUE TITLE
Single State Report

### ISSUE THREAD

**Issue by esalii** [fashberg/WThermostatBeca#54]
Hi,

Single  State report is not provided every 5 minutes, just JSON state is reporting

**Comment by Master-Rudi** [comment]
I have the same issue

Any fixes?

**Comment by fashberg** [comment]
Hey @esalii and @Master-Rudi,

right - single properties had only been sent out after they've got changed.
I've changed this so all properties are sent now out every notification interval.


Also i've renamed the option to "Send all properties also in separate MQTT messages"
