### ISSUE TITLE
Wrong state in Home Assistant

### ISSUE THREAD

**Issue by blackscreener** [fashberg/WThermostatBeca#65]
When thermostat is in auto mode (scheduler) and I change temperature in Home Assistant then the mode in HA changes to manual but mode in device stays on scheduler. So state in device and state in Home Assistant is different,

**Comment by fashberg** [comment]
Hey @blackscreener,

which version do you have installed on your thermostat?
Should be fixed with 1.17-fas

**Comment by blackscreener** [comment]
> 
> 
> Hey @blackscreener,
> 
> which version do you have installed on your thermostat?
> Should be fixed with 1.17-fas
Hey.
1.18

**Comment by dmerlani** [comment]
Hi guys, I belive I have found the solution
changed the onChangeTargetTemperature function adding the "heat" mode command 
unsigned char deviceOnCommand[] = { 0x55, 0xAA, 0x00, 0x06, 0x00, 0x05,
        	                                    0x04, 0x04, 0x00, 0x01, 0x01};
        	commandCharsToSerial(11, deviceOnCommand);

so everytime the user changes the temperature in auto mode, it will force first to switch to heat mode and then change the temperature.

@fashberg Is it correct? can you implement the change?


void onChangeTargetTemperature(WProperty* property) {
		network->log()->trace(PSTR("Got new targetTemperature"));
		bool force=false;
		if (schedulesMode->equalsString(SCHEDULES_MODE_AUTO)){
			network->log()->trace(PSTR("Got new targetTemperature: Switching from Schdule to Manual"));
			schedulesMode->setSuppressOnChange();
			schedulesMode->setString(SCHEDULES_MODE_OFF);
			force=true;
            unsigned char deviceOnCommand[] = { 0x55, 0xAA, 0x00, 0x06, 0x00, 0x05,
        	                                    0x04, 0x04, 0x00, 0x01, 0x01};
        	commandCharsToSerial(11, deviceOnCommand);
		}
		if (schedulesMode->equalsString(SCHEDULES_MODE_OFF)){
			// only set targetTemperatureManualMode and targetTemperatureManualModeToMcu() if current mode is Manual
			if (force || !WProperty::isEqual(targetTemperatureManualMode, this->targetTemperature->getDouble(), 0.01)) {
				targetTemperatureManualMode = this->targetTemperature->getDouble();
				network->log()->trace((String(PSTR("onChangeTargetTemperature, temp: "))+String(targetTemperatureManualMode)).c_str());
				targetTemperatureManualModeToMcu();
				schedulesMode->setString(SCHEDULES_MODE_OFF);
			} else {
				network->log()->trace((String(PSTR("setTargetTemperatureNoChange, temp: "))+String(this->targetTemperature->getDouble())).c_str());
			}
		}
		updateRelaySimulation();
    }

**Comment by Tigger2014** [comment]
Hi @fashberg,

I'm seeing the same thing when asking Google assistant via home assistant to turn up the temperature, if in auto mode it does not change to manual, is the solution above the correct way to solve it?.


Many thanks

**Comment by l0cal-h05t** [comment]
hi i have the same issue, 
but if i try to compile a new version i get the following error: 
WThermostat\../lib/WAdapter/WAdapter/WJsonParser.h: In member function 'WProperty* WJsonParser::endTrue()':
WThermostat\../lib/WAdapter/WAdapter/WJsonParser.h:500:23: error: cannot convert 'bool' to 'WProperty*' in initialization

can some one help me ?

**Comment by mromaithi** [comment]
Hello guys,

Any updates on this bug.

Thanks.
