### ISSUE TITLE
Target temperature is not saved after disconnecting the device from power

### ISSUE THREAD

**Issue by YuriT1** [fashberg/WThermostatBeca#67]
Hello!
In Klaus firmware (1.15): after disconnecting the device from the power supply 220V (OFF) ,  and ==> turning on the power 220V (ON), targetTemperature = the last target temperature set on the device, but not programmatically set (for example, on the device we set the temperature 20 degrees with our hands. Then we send it to the mqtt topic == >> targetTemperature = 25. The topic publishes targetTemperature = 25. Disconnect the thermostat from 220V power == >> Next, connect the thermostat to 220V power. The topic publishes targetTemperature = 20 !!!) Is this issue resolved in this firmware?

**Comment by fashberg** [comment]
Hey @YuriT1 ,

i've examined this today. It's a Bug in MCU (Main CPU of device, not Online, which is still closed source).

See #55 

We can think about saving these values to FLASH after a change.

* mode (off/schedule/manual)
* manual target temp
* ecoMode
* lock 

i'll close this case - it get's continued at #55

Kind Regards
Folke
