### ISSUE TITLE
WthermostatBeca New Version DLX Control Solutions

### ISSUE THREAD

**Issue by alessandrosalafia** [fashberg/WThermostatBeca#69]
![97772782-776b9080-1b4a-11eb-8f2c-d5c93850dd73](https://user-images.githubusercontent.com/64415247/97775434-db994f00-1b60-11eb-9df3-a1b8d21d16e7.jpg)
Hi Folk . I recently ordered new home thermostats. It arrived and I found they have different hardware. It's still 8266 and I was able to load your firmware, but there are problems in displaying and exchanging data.  
It seems that the thermostat is not communicating correctly with HA. See and set different temperatures. I used mqtt and autodiscovery, but doesn't work better. The firmware is WThermostat 1.18-fas, but  I also tried with 1.17.
![1604062331365](https://user-images.githubusercontent.com/64415247/97708450-1b0c6080-1ab9-11eb-90c3-648f7453b2ab.jpg)
[log new Thermostat.txt](https://github.com/klausahrenberg/WThermostatBeca/files/5468789/log.new.Thermostat.txt)

**Comment by fashberg** [comment]
Hey @alessandrosalafia 

i will merge with #68 

Can you also gimme a hint where you have bought?

Kind Regards
Folke

**Comment by alessandrosalafia** [comment]
Hi Folk, 
I bought them on the official Mouse store, aliexpress. I believe they will now use this hardware for the next thermostats as well.
https://moes.aliexpress.com/store/4988128?spm=a2g0s.9042311.0.0.2ec64c4dRW7fOK
I have also attached weblogs with verbose mode. If you need other weblogs let me know.
