### ISSUE TITLE
Model not set correctly if no older settings present

### ISSUE THREAD

**Issue by J-rethinkmx** [fashberg/WThermostatBeca#88]
When starting with the current baseline code, setting the model type via the thermostat config page is not re-read into the config/settings upon reboot. The existing code always assumes oldSettings are there and uses them.

as usual there are many ways to handle this.....

fixed this in my current fork around line 442 in WBecaDevice.h

// if no current setting, then use old setting instead (and save in current settings)
if (!network->getSettings()->existsSetting(PROP_THERMOSTATMODEL))
	if (network->getSettingsOld())
	{
		this->thermostatModel = network->getSettings()->setByte(PROP_THERMOSTATMODEL,
				(network->getSettingsOld() && network->getSettingsOld()->existsSetting(PROP_THERMOSTATMODEL) ? network->getSettingsOld()->getByte(PROP_THERMOSTATMODEL) : MODEL_BHT_002_GBLW));
	}

// get the current settings value
this->thermostatModel = network->getSettings()->existsSetting(PROP_THERMOSTATMODEL) ? network->getSettings()->getSetting(PROP_THERMOSTATMODEL) : MODEL_BHT_002_GBLW;

**Comment by chipmoca** [comment]
А есть исправленная версия, попробовать? У меня MODEL_BHT_002_GBLW.
