### ISSUE TITLE
1.18 Issues in Relay State Calculation

### ISSUE THREAD

**Issue by paveq** [fashberg/WThermostatBeca#90]
Issues in relay state calculation (not showing as heating) as seen by the chart in 1.18, with these MCU parameters:

- temperature compensation set to -4
- deadband set to 2

<img width="976" alt="Screenshot 2020-12-14 at 10 40 43" src="https://user-images.githubusercontent.com/130256/102059311-62e11000-3df9-11eb-8232-c5d079e2de70.png">

**Comment by paveq** [comment]
Weird behaviour I noted with these MCU settings when i turn off the unit, and turn it back again, it starts to heat immediately when target is 22.5 and display shows 22.0. Maybe on startup the unit just behaves in a way, that is measured temp is less than target, it defaults to always heating?

**Comment by paveq** [comment]
Maybe I have wrong deadband setting in the thermostat, not sure. Seems no matter what number I input to it in settings, after refresh it always shows 1, and not the value that was stored (if it was stored?).

**Comment by richard-scott** [comment]
See: https://github.com/fashberg/WThermostatBeca/issues/47
