### ISSUE TITLE
Modbus registers?

### ISSUE THREAD

**Issue by MichielVanwelsenaere** [fashberg/WThermostatBeca#99]
Hi!

Thanks for your great work and for open sourcing it.
I'm tempted to use these Beca thermostats for my setup but would like to integrate with them via Modbus RTU.
Therefor I was hoping you could shed some light on:
- do all models expose a modbus RTU interface? On every image I find I can see 'modbus' noted down on the back but I can't see where the modbus wires need to be plugged in..
- do you have a list of the exposed modbus registers and what they contain? That information seems hard to come by, even on the Beca website I can't seem to find it.

Thank you!

**Comment by badger707** [comment]
It seems you need Modbus version thermostat.
There were some video on youtube where guy talks on this. Dont have link to it, sorry, but luckily I have done some screenshots at that time:
![BECA_MODBUS_0](https://user-images.githubusercontent.com/77490076/109303026-10c55d80-7832-11eb-877f-bc019b170326.png)

Protocol & registers
![BECA_MODBUS](https://user-images.githubusercontent.com/77490076/109303564-e7f19800-7832-11eb-984b-7e4f6bc6b6b1.png)

**Comment by MichielVanwelsenaere** [comment]
thank you very much, closing issue.
